setup: |
  echo "🐊 Start to install dependencies ..."
  echo "🐊 Note: Will not install dependencies if available"
  cd listmutator && poetry install
  echo "🐊 ... Done installing dependencies"
---

# Checks on Files {{{

# perform checks on a file
- listmutator/listmutator/__init__.py:
    - description: Ensure that the __init__.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for __init__.py in the listmutator/ directory
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/main.py:
    - description: Ensure that the main.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for main.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/approach.py:
    - description: Ensure that the approach.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for approach.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/constants.py:
    - description: Ensure that the constants.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for constants.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/generate.py:
    - description: Ensure that the generate.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for generate.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/benchmark.py:
    - description: Ensure that the benchmark.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for benchmark.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- listmutator/listmutator/singlylinkedlist.py:
    - description: Ensure that the singlylinkedlist.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for singlylinkedlist.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Add at least two assertions about the state of the SinglyLinkedList to a method
      check: MatchFileFragment
      options:
        fragment: assert
        count: 2
        exact: false

# perform checks on a file
- listmutator/listmutator/doublylinkedlist.py:
    - description: Ensure that the doublylinkedlist.py file exists in the listmutator/listmutator/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for doublylinkedlist.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Add at least two assertions about the state of the DoublyLinkedList to a method
      check: MatchFileFragment
      options:
        fragment: assert
        count: 2
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 2
        exact: true
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 16
        exact: false
    - description: Confirm that the markdown file has the correct number of lists of data or commands
      check: CountMarkdownTags
      options:
        tag: list 
        count: 3
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 4
        exact: false

# }}}

# Confirm Correctness with Linters and Checkers {{{

# run a check
- description: Pass the source code formatting checks run by ruff
  command: cd listmutator && poetry run task format

# run a check
- description: Pass the source code linting checks run by ruff
  command: cd listmutator && poetry run task check

# run a check
- description: Pass the linting checks run by pymarkdown
  command: cd listmutator && poetry run task markdownlint

# run a check
- description: Pass the undocumented function checks run by symbex
  command: cd listmutator && poetry run task symbex-documented

# run a check
- description: Pass the untyped function checks run by symbex
  command: cd listmutator && poetry run task symbex-typed

# }}}

# Program Output {{{

# run the program and confirm correct number of lines in the output
- description: Run the program and confirm the correct number of non-blank lines in the benchmark output
  check: CountCommandOutput
  options:
    command: 'cd listmutator && poetry run listmutator --operation add --startsize 10000 --runs 5 --listtype singlylinked'
    count: 14
    exact: false

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
